## Basic Example

In [27]:
from sklearn import neighbors,datasets,preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
iris=datasets.load_iris()
X,y=iris.data[:,:2],iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=33)
scaler=preprocessing.StandardScaler().fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)
model=neighbors.KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)
prediction=model.predict(X_test)
accuracy_score(y_test,prediction)


0.631578947368421

In [34]:
## Loading Datas using Numpy other libs like scipy,pandas are also Valid
import numpy as np
x=np.random.random((10,5))
z=np.array(['M','M','F','F','M','F','M','M','F','F','F'])
x[x<5]=0

### Train Test Split

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,random_state=0)


# Preprocessing The Data

In [100]:
# Standardization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X_train)
standardized_x_train=scaler.transform(X_train)
standardized_x_test=scaler.transform(X_test)
#Normalization
from sklearn.preprocessing import Normalizer
normal=Normalizer().fit(X_train)
normalized_x_train=normal.transform(X_train)
normalized_x_test=normal.transform(X_test)
#Binarization
from sklearn.preprocessing import Binarizer
binary=Binarizer().fit(X_train)
Binarized_X_train=binary.transform(X_train)
Binarized_X_test=binary.transform(X_test)

##LabelEncoder

from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
y=enc.fit_transform(y)


##imputing Missing Values
from sklearn.preprocessing import Imputer
imp=Imputer(missing_values=0,strategy='mean',axis=0)
imp.fit_.transform(X_train)


##Generating Polynomial Features
from sklearn.preprocessing import PolynomialFeatures
pf=PolynomialFeatures(5)
pf.fit_transform(X)


array([[1.00000000e+00, 5.10000000e+00, 3.50000000e+00, ...,
        1.11517875e+03, 7.65318750e+02, 5.25218750e+02],
       [1.00000000e+00, 4.90000000e+00, 3.00000000e+00, ...,
        6.48270000e+02, 3.96900000e+02, 2.43000000e+02],
       [1.00000000e+00, 4.70000000e+00, 3.20000000e+00, ...,
        7.23845120e+02, 4.92830720e+02, 3.35544320e+02],
       ...,
       [1.00000000e+00, 6.50000000e+00, 3.00000000e+00, ...,
        1.14075000e+03, 5.26500000e+02, 2.43000000e+02],
       [1.00000000e+00, 6.20000000e+00, 3.40000000e+00, ...,
        1.51084576e+03, 8.28528320e+02, 4.54354240e+02],
       [1.00000000e+00, 5.90000000e+00, 3.00000000e+00, ...,
        9.39870000e+02, 4.77900000e+02, 2.43000000e+02]])

# Create Model Supervised Learning

In [64]:
## Linear Regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression(normalize=True)

## Support vector Machine
from sklearn import svm
model=svm.SVC(kernel='linear')

## Naives Bayes
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB()

## KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

## MOdel Fitting
lr.fit(X_train,y_train)
model.fit(X_train,y_train)
clf.fit(X_train,y_train)
knn.fit(X_train,y_train)

##prediction
y_predict=lr.predict(X_test)
y_predict=model.predict(np.random.random((2,5)))
y_predict=clf.predict(X_test)
y_predict=knn.predict_proba(X_test)

KNeighborsClassifier()

# Unsupervised Learning

In [81]:
## Principal Component Analysis

from sklearn.decomposition import PCA
pca=PCA(n_components=0.95)

## KMeans
from sklearn.cluster import KMeans
k_means=KMeans(n_clusters=5,random_state=0)

## Model_Fitting
k_means.fit(X_train)
pca_model=pca.fit_transform(X_train)

## Predictions
y_pred=k_means.predict(X_test)
y_pred

array([0, 4, 1, 0, 0, 0, 1, 1, 0, 4, 4, 1, 0, 0, 4, 0, 0, 1, 0, 4, 1, 2,
       0, 1, 3, 0, 0, 0, 0, 0, 3, 4, 0, 0, 4, 0, 0, 0])


# Evaluation

In [85]:
## Accuracy Score
knn.score(X_test,y_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction)

## Classification Report
from sklearn.metrics import classification_report
classification_report(y_test,prediction)

## Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

##Regression Metrics
from sklearn.metrics import mean_absolute_error
y_true=[3,-0.5,2]
mean_absolute_error(y_true,y_predict)

## Mean Squared Error
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_predict)

##R2 score
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

##Clustering Metrics 1.Adjusted Rand Index
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_test,y_predict)
##Homogeneity
from sklearn.metrics import homogeneity_score
homogeneity_score(y_test,y_predict)

## V-measure
from sklearn.metrics import v_measure_score
metrics.v_measure_score(y_test,y_predict)


array([[ 8,  0,  0],
       [ 0,  8,  3],
       [ 0, 11,  8]], dtype=int64)

In [88]:
from sklearn.cross_validation import cross_val_score
cross_val_score(knn,X_train,y_train,cv=4)
cross_val_score(lr,X_train.y_train,cv=2)

ModuleNotFoundError: No module named 'sklearn.cross_validation'

# Tune Your Model

In [93]:
from sklearn.grid_search import GridSearchCV
params={"n_neighbors":np.arange(1,3),"metric":["euclidean","cityblock"]}
grid=GridSearchCV(estimator=knn,param_grid=params)
grid.fit(X_train,y_train)
print(grid.best_score_)
print(grid.best_estimator_.n_neighbors)


## Randomized Search CV
from sklearn.grid_search import RandomizedSearchCV
params={"n_neighbors": np.arange(1,5),
       "weights":["uniform","distance"]}
rsearch=RandomizedSearchCV(estimator=knn,param_distributions=params,cv=4,n_iter=8,random_state=5)
rsearch.fit(X_train,y_train)
print(rsearch.best_score_)


ModuleNotFoundError: No module named 'sklearn.grid_search'